// <auto-generated />
namespace TreeViewMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change1233 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change1233));
        
        string IMigrationMetadata.Id
        {
            get { return "202401151618008_change1233"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
